name: goreleaser

# Keep in mind that the first run of this workflow will probable be pushed
# without tags, so it will fail on the git command.

on:
  push:
    branches: [latest]
    tags: ["v*"]

concurrency:
  group: ci-push-version-${{ github.ref }}
  cancel-in-progress: true

jobs:
  goreleaser:
    uses: ./.github/workflows/_goreleaser.yml
  docker-buildx:
    needs: goreleaser
    uses: ./.github/workflows/_docker-buildx.yml
